name: Infrastructure Deploy (Terraform + Ansible)

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'playbook/**'
      - 'inventory/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      terraform_action:
        description: 'Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - skip
      run_ansible:
        description: 'Run Ansible after Terraform'
        required: true
        default: true
        type: boolean

jobs:
  terraform:
    if: github.event.inputs.terraform_action != 'skip'
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment || 'staging' }}
      action: ${{ github.event.inputs.terraform_action || 'apply' }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

  get-terraform-outputs:
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event.inputs.run_ansible != 'false' && needs.terraform.result == 'success'
    outputs:
      hosts: ${{ steps.parse-outputs.outputs.hosts }}
    
    steps:
    - name: Download Terraform outputs
      uses: actions/download-artifact@v3
      with:
        name: terraform-outputs-${{ github.event.inputs.environment || 'staging' }}

    - name: Parse Terraform outputs
      id: parse-outputs
      run: |
        # Extract IP addresses or hostnames from Terraform outputs
        # Adjust this based on your actual Terraform outputs
        if [ -f terraform-outputs.json ]; then
          # Example: extract server IPs from outputs
          hosts=$(jq -r '.server_ips.value[]? // empty' terraform-outputs.json | tr '\n' ',' | sed 's/,$//')
          echo "hosts=${hosts}" >> $GITHUB_OUTPUT
        else
          echo "hosts=" >> $GITHUB_OUTPUT
        fi

  ansible:
    needs: [terraform, get-terraform-outputs]
    if: github.event.inputs.run_ansible != 'false' && needs.terraform.result == 'success'
    uses: ./.github/workflows/environment-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment || 'staging' }}
      playbook: 'playbook/test.yml'
    secrets:
      ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      TARGET_HOST: ${{ needs.get-terraform-outputs.outputs.hosts || secrets.TARGET_HOST }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}